# beachfront-py
# https://github.com/venicegeo/beachfront-py

# Copyright 2016, RadiantBlue Technologies, Inc.

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

version: '2'

services:

  base:
    build:
      context: .
    image: "venicegeo/beachfront:latest"
    entrypoint: /bin/bash
    volumes:
      - '.:/work:rw'

  test:
    image: "venicegeo/beachfront:latest"
    command: bash -c 'nosetests --with-coverage --cover-inclusive --cover-package beachfront -v -s;'
    working_dir: /work
    volumes:
      - '.:/work:rw'
